export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SET_SELECTED_PRODUCT",
    SET_PROD_SEARCH_TEXT:"SET_PROD_SEARCH_TEXT",
    SET_DEPARTMENT:"SET_DEPARTMENT",
    ADD_TO_CART:"ADD_TO_CART",
    ADD_TO_WISHLIST:"ADD_TO_WISHLIST",
    UPDATE_ITEM_QTY:"UPDATE_ITEM_QTY",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST"
}